services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./conf/.htpasswd:/conf/.htpasswd
      - ./logs:/logs
      - ./src/static:/static
      - ./src/private:/private
      - ./src/internal:/internal
  db:
    container_name: db
    image: postgres:alpine
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - PGDB_VENDOR=postgres
      - PGDATA=/var/lib/postgresql/data
    restart: always

  web:
    build:
      context: .
    container_name: backend
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src:/usr/src/app
    env_file:
      - .env
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
    restart: always
    depends_on:
      - db
